# Generated by Django 2.1 on 2018-10-03 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailmanager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Manager',
                'db_table': 'email_manager',
            },
        ),
        migrations.CreateModel(
            name='PhoneManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('country_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonemanager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Phone Manager',
                'db_table': 'phone_manager',
            },
        ),
    ]
