# Generated by Django 2.1 on 2018-09-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmanager',
            options={'verbose_name_plural': 'Email Manager'},
        ),
        migrations.AlterModelOptions(
            name='phonemanager',
            options={'verbose_name_plural': 'Phone Manager'},
        ),
        migrations.AddField(
            model_name='phonemanager',
            name='country_code',
            field=models.CharField(default=84, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonemanager',
            name='pin',
            field=models.CharField(default='613349', max_length=6),
        ),
    ]
