# Generated by Django 2.1 on 2018-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemanager',
            name='sent',
        ),
        migrations.AlterField(
            model_name='emailmanager',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='phonemanager',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='phonemanager',
            name='pin',
            field=models.CharField(default='675311', max_length=6),
        ),
    ]
