# Generated by Django 2.1 on 2018-09-18 07:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiggerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=80, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to answer')], default='P', max_length=1)),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
                ('profile_picture', models.ImageField(blank=True, default='default/avatar-default.jpg', max_length=255, null=True, upload_to=core.models.photo_upload_to)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zip_code', models.IntegerField(blank=True, default=0, null=True)),
                ('firebase_token', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_token', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
