# Generated by Django 2.1 on 2018-09-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biggeruser',
            options={'verbose_name_plural': 'Bigger Users'},
        ),
    ]
