# Generated by Django 2.1 on 2018-10-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biggeruser',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='biggeruser',
            name='phone_number',
        ),
    ]
