# Generated by Django 2.1 on 2018-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180918_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biggeruser',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
