# Generated by Django 2.1 on 2018-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181003_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biggeruser',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='biggeruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
