# Generated by Django 2.1 on 2018-09-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='privileged_id',
            new_name='privileged',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='topic',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularys', to='topics.Topic'),
            preserve_default=False,
        ),
    ]
