# Generated by Django 2.1 on 2018-09-19 07:02

from django.db import migrations, models
import topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180919_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(blank=True, default='topics/default/default.jpg', max_length=255, null=True, upload_to=topics.models.photo_upload_to),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='langguage_meaning',
            field=models.CharField(blank=True, default='en', max_length=4),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='langguage_source',
            field=models.CharField(blank=True, default='en', max_length=4),
        ),
    ]
