# Generated by Django 2.1 on 2018-09-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
