# Generated by Django 2.1 on 2018-09-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20180919_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfo',
            options={'verbose_name_plural': 'AppInfo'},
        ),
        migrations.AlterModelTable(
            name='appinfo',
            table='appinfo',
        ),
    ]
