# Generated by Django 2.1 on 2018-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180919_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
